### ISSUE TITLE
Failing when preloading

### ISSUE THREAD

**Issue by onemanstartup** [davydovanton/rspec-hanami#1]
`~Code/Experiment/oneman/spec/support/capybara.rb:5:in `included': uninitialized constant RSpec::Hanami::Container (NameError)`

Hanami head version.

**Comment by davydovanton** [comment]
Hello, thanks for reporting 👍 
Could you provide more information about this problem?

**Comment by onemanstartup** [comment]
Failed here basically
```
  config.include RSpec::FeatureExampleGroup
```
Log
```
/Users/onemanstartup/Code/Experiment/oneman/spec/support/capybara.rb:5:in `included': uninitialized constant RSpec::Hanami::Container (NameError)
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1312:in `include'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1312:in `safe_include'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1261:in `block in configure_existing_groups'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1259:in `each'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1259:in `configure_existing_groups'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1161:in `include'
	from /Users/onemanstartup/Code/Experiment/oneman/spec/features_helper.rb:8:in `block in <top (required)>'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core.rb:97:in `configure'
	from /Users/onemanstartup/Code/Experiment/oneman/spec/features_helper.rb:7:in `<top (required)>'
	from /Users/onemanstartup/Code/Experiment/oneman/spec/web/features/visit_home_spec.rb:1:in `require'
	from /Users/onemanstartup/Code/Experiment/oneman/spec/web/features/visit_home_spec.rb:1:in `<top (required)>'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/onemanstartup/Code/Experiment/oneman/.gem/ruby/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<main>'
```

**Comment by lightalloy** [comment]
I also ran into this problem. Had to change 
```ruby
Capybara.app = Hanami::Container.new
``` 
to 
```ruby
Capybara.app = ::Hanami::Container.new
``` 
in spec/support/capybara.rb, so it worked.

**Comment by blewa** [comment]
lightalloy's fix also works for the `::hanami::App.new case`.

**Comment by davydovanton** [comment]
I updated installation information for this case. Thanks everyone 🎉

**Comment by augustoc100** [comment]
Hanami.app it works too
